set(_CATKIN_CURRENT_PACKAGE "homework4")
set(homework4_MAINTAINER "abc <abc@todo.todo>")
set(homework4_DEPRECATED "")
set(homework4_VERSION "0.0.0")
set(homework4_BUILD_DEPENDS "dynamic_reconfigure" "roscpp" "tf" "visualization_msgs")
set(homework4_RUN_DEPENDS "dynamic_reconfigure" "roscpp" "tf" "visualization_msgs")
set(homework4_BUILDTOOL_DEPENDS "catkin")